schedule_interval: "30 * * * *"

home_path: 'adlogs/log_process/'


parent_directory: 'stage_{}_logs_dev'
log_path: 'log/*'



tables:
    - imp
    - click
    - state
    - int

imp:
    - ipn_blacklist
    - smart_clip_patch

state: 
    - ipn_blacklist

int:
    - set_interaction_smartclip_placement

click:
    - ipn_blacklist
    - smart_clip_patch
